version: '3.8'

services:
  postgres_key:
    image: postgres:latest
    container_name: postgres_key
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_key
    ports:
      - "5432:5432"
    volumes:
      - postgres_key:/var/lib/postgresql/datas
    networks:
      - app_network

  keycloak_web:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_key:5432/postgres_key
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - postgres_key
    ports:
      - "8080:8080"
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: staff_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: staff_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_key:
  postgres_data:

networks:
  app_network:
    driver: bridge
