server:
  port: 8900

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/staff_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
